name: 04 - Events
on:
    issues:
        types:
            - opened
            - reopened
    issue_comment:
        types: [created]
    pull_request_review_comment:
        types:
            - created

jobs:
    inspect-event:
        runs-on: ubuntu-24.04
        permissions:
            issues: write
        steps:
            - name: Mostrar información del evento
              run: |
                  echo "Evento recibido: ${{ github.event_name }}"
                  echo "Número de issue o PR: ${{ github.event.issue.number }}"
                  if [ -n "${{ github.event.comment.body }}" ]; then
                      echo "Comentario: ${{ github.event.comment.body }}"
                  fi
            - name: Publicar comentario como bot
              if: github.event_name == 'issues' && github.event.action == 'opened'
              env:
                  REPO: ${{ github.repository }}
                  ISSUE_NUMBER: ${{ github.event.issue.number }}
              run: |
                gh issue comment $ISSUE_NUMBER --body "¡Gracias por abrir un issue en ${{ github.repository }}! Nuestro equipo lo revisará pronto. "