name: 05 - CI
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
defaults:
  run:
    working-directory: 12-ejercicio-cicd   # Para evitar escribir `cd` en cada job, podemos simplificarlo con esta linea

jobs:
    frontend-lint:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Usar composite action para instalar pnpm y node
              uses: ./.github/actions/setup-pnpm-ci-cd
        
            - name: Ejectuar scripts del monorepo
              run: |
                  echo "::group::Lint"
                  pnpm lint:frontend
                  echo "::endgroup::"
                  
    frontend-test: 
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6 

            - name: Usar composite action para instalar pnpm y node
              uses: ./.github/actions/setup-pnpm-ci-cd

            - name: Ejectuar scripts del monorepo
              run: |
                  pnpm test:frontend

    backend-lint: 
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6 

            - name: Usar composite action para instalar pnpm y node
              uses: ./.github/actions/setup-pnpm-ci-cd

            - name: Ejectuar scripts del monorepo
              run: |
                  pnpm lint:backend

    backend-test:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6 

            - name: Usar composite action para instalar pnpm y node
              uses: ./.github/actions/setup-pnpm-ci-cd

            - name: Ejectuar scripts del monorepo
              run: |
                  pnpm test:backend

    frontend-build:
        #Solo se ejecuta si frontend-lint y frontend-test son exitosos
        needs: [frontend-lint, frontend-test]
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6 

            - name: Usar composite action para instalar pnpm y node
              uses: ./.github/actions/setup-pnpm-ci-cd

            - name: Ejecutar scripts del monorepo
              run: |
                  pnpm build:frontend
        
    backend-build:
        #Solo se ejecuta si backend-lint y backend-test son exitosos
        needs: [backend-lint, backend-test]
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout code
              uses: actions/checkout@v6 

            - name: Usar composite action para instalar pnpm y node
              uses: ./.github/actions/setup-pnpm-ci-cd

            - name: Ejecutar scripts del monorepo
              run: |
                  pnpm build:backend
        
    frontend-test-matrix:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-24.04, macos-latest, windows-latest]
                node: ['22', '24']

        steps:
            - name: Checkout code
              uses: actions/checkout@v6

            - name: Usar composite action para instalar pnpm y node
              uses: ./.github/actions/setup-pnpm-ci-cd
              with:
                node-version: ${{ matrix.node }}

            - name: Ejecutar tests del frontend
              working-directory: ./12-ejercicio-cicd
              run: pnpm test:frontend